version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: local-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-stack-server --appendonly yes --requirepass mysecretpassword

  redis-insight:
    image: redis/redisinsight:latest
    container_name: local-redis-insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis

volumes:
  redis_data:
  redis_insight_data: